table _Medidas
	lineageTag: 5d8e9f0a-1b2c-3d4e-5f6a-7b8c9d0e1f2a

	measure 'Preco Selecionado' =
			VAR _selecao = SELECTEDVALUE('Parâmetro'[Parâmetro Pedido])
			RETURN IF(_selecao = 0, [Preco Base BRL], [Preco Base USD])
		formatString: #,##0.00
		displayFolder: [01] Base
		lineageTag: e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b

	measure 'Market Cap Selecionado' =
			VAR _selecao = SELECTEDVALUE('Parâmetro'[Parâmetro Pedido])
			RETURN IF(_selecao = 0, [Market Cap Base BRL], [Market Cap Base USD])
		formatString: #,##0.00
		displayFolder: [01] Base
		lineageTag: f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c

	measure 'Market Cap Base BRL' = SUM(vw_Dashboard_Completa[Market_Cap_BRL])
		formatString: #,##0.00
		displayFolder: [01] Base\Market Cap
		lineageTag: c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f

	measure 'Variacao Dinamica %' = ```
			
			VAR _IndexSelecionado = SELECTEDVALUE('Parâmetro 2'[Parâmetro Pedido])
			
			VAR _Dias = 
			    SWITCH( _IndexSelecionado,
			        0, 7,   -- Ultimos_7_Dias
			        1, 14,  -- Ultimos_14_Dias
			        2, 30,  -- Ultimos_30_Dias
			        3, 60,  -- Ultimos_60_Dias
			        4, 90,  -- Ultimos_90_Dias
			        5, 180, -- Ultimos_180_Dias
			        6, 365, -- Ultimo_Ano
			        7, 0    -- Todo Periodo
			    )
			
			VAR _DataMaxPeriodo = 
			    CALCULATE(
			        MAX(vw_Calendario_Dinamico[Data]),
			        SWITCH( _IndexSelecionado,
			            0, vw_Calendario_Dinamico[Ultimos_7_Dias] = "Sim",
			            1, vw_Calendario_Dinamico[Ultimos_14_Dias] = "Sim",
			            2, vw_Calendario_Dinamico[Ultimos_30_Dias] = "Sim",
			            3, vw_Calendario_Dinamico[Ultimos_60_Dias] = "Sim",
			            4, vw_Calendario_Dinamico[Ultimos_90_Dias] = "Sim",
			            5, vw_Calendario_Dinamico[Ultimos_180_Dias] = "Sim",
			            6, vw_Calendario_Dinamico[Ultimo_Ano] = "Sim",
			            7, MAX(vw_Calendario_Dinamico[Data]) 
			        ),
			        REMOVEFILTERS(vw_Calendario_Dinamico)
			    )
			
			VAR _Atual = 
			    CALCULATE(
			        [Preco Selecionado],
			        DATESINPERIOD(
			            vw_Calendario_Dinamico[Data], 
			            _DataMaxPeriodo, 
			            -_Dias, 
			            DAY
			        )
			    )
			
			VAR _Anterior = 
			    CALCULATE(
			        [Preco Selecionado],
			        DATESINPERIOD(
			            vw_Calendario_Dinamico[Data], 
			            _DataMaxPeriodo - _Dias, 
			            -_Dias, 
			            DAY
			        ),
			        REMOVEFILTERS(vw_Calendario_Dinamico) 
			    )
			
			RETURN
			    IF(
			        _Dias > 0 && NOT ISBLANK(_Anterior),
			        DIVIDE(_Atual - _Anterior, _Anterior)
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: [02] Performance\Variações
		lineageTag: a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d

	measure 'Drawdown %' =
			VAR _Topo = [Maxima Historica]
			VAR _Atual = [Preco Selecionado]
			RETURN DIVIDE(_Atual - _Topo, _Topo)
		formatString: 0.00%
		displayFolder: [03] Analise Tecnica\Risco
		lineageTag: a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d

	measure 'Variacao Nominal' = [Preco Selecionado] - CALCULATE([Preco Selecionado], DATEADD(vw_Calendario_Dinamico[Data], -1, DAY))
		formatString: #,##0.00
		displayFolder: [02] Performance\Variações
		lineageTag: b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e

	measure 'Icone Tendencia' =
			VAR _var = [Variacao Dinamica %]
			RETURN IF(_var > 0, "▲", "▼")
		displayFolder: [05] Storytelling\Visual
		lineageTag: a9b0c1d2-e3f4-4a5b-6c7d-8e9f0a1b2c3d

	measure 'Media Movel 30 Dias' = ```
			
			VAR _UltimaDataVisivel = MAX('vw_Calendario_Dinamico'[Data])
			RETURN
			    AVERAGEX(
			        FILTER(
			            ALLSELECTED('vw_Calendario_Dinamico'),
			            'vw_Calendario_Dinamico'[Data] > _UltimaDataVisivel - 30 && 
			            'vw_Calendario_Dinamico'[Data] <= _UltimaDataVisivel
			        ),
			        [Preco Selecionado]
			    )
			
			```
		formatString: #,##0.00
		displayFolder: [02] Performance\Médias
		lineageTag: d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a

	measure 'Preco Base BRL' = MAX(vw_Dashboard_Completa[Preco_BRL])
		formatString: #,##0.00
		displayFolder: [01] Base\Preços
		lineageTag: a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d

	measure 'Preco Base USD' = MAX(vw_Dashboard_Completa[Preco_USD])
		formatString: #,##0.00
		displayFolder: [01] Base\Preços
		lineageTag: b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e

	measure 'Market Cap Base USD' = SUM(vw_Dashboard_Completa[Market_Cap_USD])
		formatString: #,##0.00
		displayFolder: [01] Base\Market Cap
		lineageTag: d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a

	measure 'Media Movel 7 Dias' =
			AVERAGEX(
				DATESINPERIOD(vw_Calendario_Dinamico[Data], LASTDATE(vw_Calendario_Dinamico[Data]), -7, DAY),
				[Preco Selecionado]
			)
		formatString: #,##0.00
		displayFolder: [02] Performance\Médias
		lineageTag: c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f

	measure 'Maxima Historica' =
			CALCULATE(
				MAXX(vw_Dashboard_Completa, [Preco Selecionado]),
				ALL(vw_Calendario_Dinamico)
			)
		formatString: #,##0.00
		displayFolder: [03] Analise Tecnica\Extremos
		lineageTag: e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b

	measure 'Minima Historica' =
			CALCULATE(
				MINX(vw_Dashboard_Completa, [Preco Selecionado]),
				ALL(vw_Calendario_Dinamico)
			)
		formatString: #,##0.00
		displayFolder: [03] Analise Tecnica\Extremos
		lineageTag: f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c

	measure 'Volatilidade (Desvio Padrao)' = STDEVX.P(vw_Dashboard_Completa, [Variacao Dinamica %])
		formatString: 0.00%
		displayFolder: [03] Analise Tecnica\Risco
		lineageTag: b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e

	measure 'Preco WoW %' =
			VAR _Atual = [Preco Selecionado]
			VAR _Anterior = CALCULATE([Preco Selecionado], DATEADD(vw_Calendario_Dinamico[Data], -7, DAY))
			RETURN DIVIDE(_Atual - _Anterior, _Anterior)
		formatString: 0.00%
		displayFolder: [04] Comparativos\Temporal
		lineageTag: c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f

	measure 'Preco MoM %' =
			VAR _Atual = [Preco Selecionado]
			VAR _Anterior = CALCULATE([Preco Selecionado], DATEADD(vw_Calendario_Dinamico[Data], -1, MONTH))
			RETURN DIVIDE(_Atual - _Anterior, _Anterior)
		formatString: 0.00%
		displayFolder: [04] Comparativos\Temporal
		lineageTag: d6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a

	measure 'Market Share %' =
			VAR _CapAtivo = [Market Cap Selecionado]
			VAR _CapTotal = CALCULATE([Market Cap Selecionado], ALL(d_moedas))
			RETURN DIVIDE(_CapAtivo, _CapTotal)
		formatString: 0.00%
		displayFolder: [04] Comparativos\Mercado
		lineageTag: e7f8a9b0-c1d2-4e3f-4a5b-6c7d8e9f0a1b

	measure 'Cor Condicional Tendencia' =
			VAR _var = [Variacao Dinamica %]
			RETURN SWITCH(TRUE(), _var > 0, "#00E676", _var < 0, "#FF1744", "#BDBDBD")
		displayFolder: [05] Storytelling\Visual
		lineageTag: f8a9b0c1-d2e3-4f4a-5b6c-7d8e9f0a1b2c

	measure 'Titulo Dinamico Dashboard' =
			VAR _Ativo = SELECTEDVALUE(d_moedas[Nome_Completo], "Mercado Global")
			VAR _Moeda = SELECTEDVALUE('Parâmetro'[Parâmetro], "BRL")
			RETURN UPPER(_Ativo) & " - ANÁLISE EM " & _Moeda
		displayFolder: [05] Storytelling\Texto
		lineageTag: b0c1d2e3-f4a5-4b6c-7d8e-9f0a1b2c3d4e

	measure 'Preco Minigrafico Dinamico' = ```
			
			VAR _IndexSelecionado = SELECTEDVALUE('Parâmetro 2'[Parâmetro Pedido])
			
			VAR _Dias = 
			    SWITCH( _IndexSelecionado,
			        0, 7, 
			        1, 14, 
			        2, 30, 
			        3, 60, 
			        4, 90, 
			        5, 180, 
			        6, 365,
			        9999 -- Um número grande para "Todo Período"
			    )
			
			-- Pegamos a última data global disponível no contexto
			VAR _DataMax = CALCULATE(MAX(vw_Calendario_Dinamico[Data]), ALLSELECTED(vw_Calendario_Dinamico))
			
			RETURN
			CALCULATE(
			    [Preco Selecionado],
			    DATESINPERIOD(
			        vw_Calendario_Dinamico[Data],
			        _DataMax,
			        -_Dias,
			        DAY
			    )
			)
			```
		displayFolder: [02] Performance\Variações
		lineageTag: 7ecd61e6-d568-4daf-908f-03a6ccb9518d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ocultar Datas Minigrafico' = ```
			
			VAR _IndexSelecionado = SELECTEDVALUE('Parâmetro 2'[Parâmetro Pedido])
			
			VAR _Dias = 
			    SWITCH( _IndexSelecionado,
			        0, 7, 1, 14, 2, 30, 3, 60, 4, 90, 5, 180, 6, 365, 
			        9999 -- Todo período
			    )
			
			VAR _DataMax = CALCULATE(MAX(vw_Calendario_Dinamico[Data]), ALLSELECTED(vw_Calendario_Dinamico))
			VAR _DataMin = _DataMax - _Dias
			
			-- Verifica se a data da linha está dentro do range selecionado
			RETURN
			IF(
			    MAX(vw_Calendario_Dinamico[Data]) > _DataMin && MAX(vw_Calendario_Dinamico[Data]) <= _DataMax,
			    1,
			    0
			)
			```
		formatString: 0
		lineageTag: 218a9734-4454-4314-b96b-4a1a453aea5c

	measure 'Eixo Y Maximo' = ```
			
			VAR _MaxPreco = 
			    MAXX(
			        ALLSELECTED('vw_Calendario_Dinamico'), 
			        [Preco Selecionado]
			    )
			VAR _MaxMedia = 
			    MAXX(
			        ALLSELECTED('vw_Calendario_Dinamico'), 
			        [Media Movel 30 Dias]
			    )
			
			RETURN 
			    MAX(_MaxPreco, _MaxMedia) * 1.1
			```
		displayFolder: [05] Storytelling
		lineageTag: 52fc527a-188c-4297-b0fd-abe6c4b423c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eixo Y Minimo' = ```
			
			VAR _MinPreco = 
			    MINX(
			        ALLSELECTED('vw_Calendario_Dinamico'), 
			        [Preco Selecionado]
			    )
			VAR _MinMedia = 
			    MINX(
			        ALLSELECTED('vw_Calendario_Dinamico'), 
			        [Media Movel 30 Dias]
			    )
			
			RETURN 
			    MIN(_MinPreco, _MinMedia) * 0.9
			```
		displayFolder: [05] Storytelling
		lineageTag: 4188292f-e11d-4afe-8da5-72140bc18412

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Preco Atual' = ```
			
			LASTNONBLANKVALUE(
			    vw_Calendario_Dinamico[Data], 
			    [Preco Selecionado]
			)
			```
		formatString: 0.00
		displayFolder: [01] Base\Preços
		lineageTag: 66865c03-3d58-4e2b-aef4-8b1970bbe709

	measure 'Variacao 24h %' = ```
			
			VAR _UltimaDataComDados = 
			    MAXX(
			        FILTER(
			            ALLSELECTED('vw_Calendario_Dinamico'),
			            NOT ISBLANK([Preco Selecionado])
			        ),
			        'vw_Calendario_Dinamico'[Data]
			    )
			
			VAR _DataOntem = _UltimaDataComDados - 1
			
			VAR _PrecoHoje = 
			    CALCULATE(
			        [Preco Selecionado],
			        'vw_Calendario_Dinamico'[Data] = _UltimaDataComDados,
			        REMOVEFILTERS('vw_Calendario_Dinamico')
			    )
			
			VAR _PrecoOntem = 
			    CALCULATE(
			        [Preco Selecionado],
			        'vw_Calendario_Dinamico'[Data] = _DataOntem,
			        REMOVEFILTERS('vw_Calendario_Dinamico')
			    )
			
			RETURN
			    IF(
			        NOT ISBLANK(_PrecoHoje) && NOT ISBLANK(_PrecoOntem),
			        DIVIDE(_PrecoHoje - _PrecoOntem, _PrecoOntem)
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: [02] Performance\Variações
		lineageTag: 17e6f3ad-fb66-47a6-a1bd-3ecf3fff6dcf

	measure Atual = ```
			
			VAR _DataHoje = MAX(vw_Calendario_Dinamico[Data])
			VAR _DataOntem = _DataHoje - 1
			
			RETURN
			    CALCULATE(
			        [Preco Selecionado], 
			        vw_Calendario_Dinamico[Data] = _DataHoje,
			        REMOVEFILTERS(vw_Calendario_Dinamico[Data]) 
			    )
			
			```
		displayFolder: [01] Base\Preços
		lineageTag: 611427b3-576f-407a-a4f9-a55f1bcf0a09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure St_preco_atual = ```
			
			VAR _Selecao = SELECTEDVALUE('Parâmetro'[Parâmetro Pedido])
			VAR _Parametro = 
			IF(
			    _Selecao = 0, "(R$)", "($)")
			
			RETURN
			
			"Current price " & _Parametro
			```
		displayFolder: [05] Storytelling
		lineageTag: a113c6d6-1ab4-426f-9d5b-d9b5aa7edfb3

	measure St_variacao = ```
			
			VAR _Selecao = SELECTEDVALUE('Parâmetro'[Parâmetro Pedido])
			VAR _Parametro = 
			IF(
			    _Selecao = 0, "(R$)", "($)")
			
			RETURN
			
			"24-hour variation % " & _Parametro
			```
		displayFolder: [05] Storytelling
		lineageTag: 4bee4feb-0e57-4825-a48c-14d3a16932c8

	measure St_Maxima = ```
			
			VAR _Selecao = SELECTEDVALUE('Parâmetro'[Parâmetro Pedido])
			VAR _Parametro = 
			IF(
			    _Selecao = 0, "(R$)", "($)")
			
			RETURN
			
			"Historical Maximum " & _Parametro
			```
		displayFolder: [05] Storytelling
		lineageTag: 052c6e63-9626-41ca-8426-6b3147af8e18

	measure St_Minima = ```
			
			VAR _Selecao = SELECTEDVALUE('Parâmetro'[Parâmetro Pedido])
			VAR _Parametro = 
			IF(
			    _Selecao = 0, "(R$)", "($)")
			
			RETURN
			
			"Historic Low " & _Parametro
			```
		displayFolder: [05] Storytelling
		lineageTag: 453c3550-7991-4689-939a-30541d7b1fc4

	measure 'HTML Lista Cripto' = ```
			
			VAR _CSS = "
			    <style>
			        /* Container geral */
			        .container { 
			            font-family: 'Segoe UI', sans-serif; 
			            background-color: transparent; 
			        }
			        ::-webkit-scrollbar {
			            width: 6px;
			        }
			        ::-webkit-scrollbar-track {
			            background: transparent; 
			        }
			        ::-webkit-scrollbar-thumb {
			            background: #CCCCCC; 
			            border-radius: 10px;
			        }
			        ::-webkit-scrollbar-thumb:hover {
			            background: #888; 
			        }
			        /* Estilo de cada linha (Card do Ativo) */
			        .row { 
			            display: flex; 
			            align-items: center; 
			            justify-content: space-between; 
			            padding: 15px 20px; 
			            margin-bottom: 4px; 
			            background-color: #FFFFFF; /* Fundo Branco */
			            border-radius: 8px; /* Arredondei um pouco mais */
			            border-left: 4px solid transparent; 
			            transition: all 0.2s ease-in-out;
			            box-shadow: 0 2px 5px rgba(0,0,0,0.05); /* Sombra suave para destacar do fundo branco */
			        }
			
			        /* --- MUDANÇA 4: Efeito ao passar o mouse (Hover Azul Claro) --- */
			        .row:hover { 
			            background-color: #E1F5FE; /* Azul claro suave */
			            border-left: 4px solid #00B0FF; /* Azul um pouco mais forte na borda */
			            transform: translateX(4px); 
			        }
			
			        /* Coluna da Esquerda (Foto e Nome) */
			        .left-col { display: flex; align-items: center; gap: 15px; }
			        
			        /* --- MUDANÇA 1: Borda na logo --- */
			        .crypto-img { 
			            width: 36px; /* Aumentei ligeiramente a imagem */
			            height: 36px; 
			            border-radius: 50%; 
			            object-fit: cover; 
			            background-color: white; 
			            border: 1px solid #000000; /* Borda preta fina adicionada aqui */
			        }
			        
			        .crypto-name { 
			            color: #000000; /* Texto Preto */
			            font-weight: 700; 
			            font-size: 15px; /* Aumentei ligeiramente */
			        }
			
			        /* Coluna da Direita (Preço e Badge) */
			        .right-col { 
			            text-align: right; 
			            display: flex; 
			            flex-direction: column; 
			            align-items: flex-end; 
			            gap: 6px;
			        }
			        
			        /* --- MUDANÇA 2: Preço maior e preto --- */
			        .price { 
			            color: #000000; /* Cor preta */
			            font-weight: 700; /* Mais negrito */
			            font-size: 18px; /* Aumentado para 18px (era 13px) */
			        }
			        
			        /* --- MUDANÇA 3: Porcentagem maior --- */
			        .badge { 
			            display: flex;
			            align-items: center;
			            justify-content: center;
			            padding: 4px 10px; 
			            border-radius: 6px; 
			            font-size: 13px; /* Aumentado para 13px (era 11px) */
			            font-weight: 700; 
			            min-width: 65px;
			        }
			    </style>
			"
			
			VAR _Linhas = 
			    CONCATENATEX(
			        TOPN(50, ALL('d_moedas'), [Preco Atual], DESC), 
			        VAR _Img = 'd_moedas'[URL_Imagem]
			        VAR _Nome = 'd_moedas'[Ativo]
			        VAR _Preco = FORMAT([Preco Atual], "R$ #,##0.00")
			        VAR _Var = [Variacao Dinamica %] 
			        
			        -- Cores Condicionais (Ajustei o fundo verde/vermelho para ser um pouco mais forte para contrastar com o fundo branco)
			        VAR _CorTextoBadge = IF(_Var >= 0, "#008000", "#D32F2F") -- Verde e Vermelho mais escuros para leitura em fundo claro
			        VAR _CorFundoBadge = IF(_Var >= 0, "rgba(76, 175, 80, 0.25)", "rgba(244, 67, 54, 0.25)")
			        VAR _Seta = IF(_Var >= 0, "▲", "▼")
			        
			        RETURN
			        "<div class='row'>
			            <div class='left-col'>
			                <img src='" & _Img & "' class='crypto-img' onerror=""this.style.visibility='hidden'"">
			                <span class='crypto-name'>" & _Nome & "</span>
			            </div>
			            <div class='right-col'>
			                <div class='price'>" & _Preco & "</div>
			                <div class='badge' style='background-color: " & _CorFundoBadge & "; color: " & _CorTextoBadge & ";'>
			                    " & _Seta & " " & FORMAT(_Var, "0.00%") & "
			                </div>
			            </div>
			        </div>",
			        ""
			    )
			
			RETURN
			_CSS & "<div class='container'>" & _Linhas & "</div>"
			```
		lineageTag: be808757-a550-4b66-8fe9-701d23e7a2b2

	measure 'HTML Lista Noticias' = ```
			
			VAR _CSS = "
			    <style>
			        /* Container geral */
			        .container-noticias { 
			            font-family: 'Segoe UI', sans-serif; 
			            background-color: transparent; 
			        }
			         ::-webkit-scrollbar {
			            width: 6px;
			        }
			        ::-webkit-scrollbar-track {
			            background: transparent; 
			        }
			        ::-webkit-scrollbar-thumb {
			            background: #CCCCCC; 
			            border-radius: 10px;
			        }
			        ::-webkit-scrollbar-thumb:hover {
			            background: #888; 
			        }
			        /* Estilo do Card da Notícia */
			        .card-noticia {
			            background-color: #FFFFFF;
			            border-radius: 8px;
			            padding: 15px 20px;
			            margin-bottom: 8px;
			            border-left: 4px solid transparent;
			            box-shadow: 0 2px 5px rgba(0,0,0,0.05);
			            transition: all 0.2s ease-in-out;
			            display: flex;
			            flex-direction: column;
			            gap: 10px;
			        }
			
			        /* Efeito ao passar o mouse igual ao da lista de preços */
			        .card-noticia:hover {
			            background-color: #E1F5FE;
			            border-left: 4px solid #00B0FF;
			            transform: translateX(4px);
			        }
			
			        /* Etiqueta (Badge) para o nome do Ativo */
			        .badge-ativo {
			            align-self: flex-start;
			            background-color: #F5F5F5;
			            color: #333333;
			            font-weight: 700;
			            font-size: 14px;
			            padding: 4px 10px;
			            border-radius: 4px;
			            border: 1px solid #E0E0E0;
			        }
			
			        /* Título da Notícia */
			        .titulo-noticia {
			            color: #000000;
			            font-size: 18px;
			            font-weight: 500;
			            line-height: 1.4;
			        }
			    </style>
			"
			
			VAR _Linhas = 
			    CONCATENATEX(
			        'f_noticias_mercado', -- Aqui ele vai respeitar os filtros da página (ex: se clicar em Bitcoin, mostra só notícias de Bitcoin)
			        VAR _Ativo = 'f_noticias_mercado'[ativo]
			        VAR _Titulo = 'f_noticias_mercado'[titulo]
			        
			        RETURN
			        "<div class='card-noticia'>
			            <div class='badge-ativo'>" & _Ativo & "</div>
			            <div class='titulo-noticia'>" & _Titulo & "</div>
			        </div>",
			        ""
			    )
			
			RETURN
			_CSS & "<div class='container-noticias'>" & _Linhas & "</div>"
			```
		lineageTag: f8185bc1-31bd-4d8a-a69e-a5ae1b4c9aed

	partition _Medidas = m
		mode: import
		source =
				let
					Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
					#"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", Int64.Type}}),
					#"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
					#"Colunas Removidas"

	annotation PBI_ResultType = Table

